import { Category, Professional } from './types';
import { GENERATED_PROS } from './generatedPros';

export const CATS: Category[] = [
  { id: 'home', label: 'Home &\nMaintenance', icon: 'home', color: '#0d9488', subs: ['Plumber', 'Cleaner', 'Electrician', 'Painter', 'Carpenter', 'Locksmith', 'Handyman', 'Roofing'], aliases: ['fix', 'repair', 'house', 'build', 'broken', 'reparatie', 'teava', 'acoperis', 'roof', 'clean', 'curatenie'] },
  { id: 'beauty', label: 'Beauty &\nWellness', icon: 'sparkles', color: '#e11d48', subs: ['Hairdresser', 'Nail Tech', 'Massage', 'Makeup', 'Barber'], aliases: ['hair', 'nails', 'skin', 'salon', 'tuns', 'unghii', 'masaj', 'makeup', 'spa'] },
  { id: 'auto', label: 'Auto &\nTransport', icon: 'truck', color: '#ea580c', subs: ['Mechanic', 'MOT', 'Valeting', 'Recovery', 'Transport Auto'], aliases: ['car', 'driving', 'vehicle', 'masina', 'mecanic', 'tractare', 'auto', 'platforma', 'transport auto'] },
  { id: 'events', label: 'Events', icon: 'party-popper', color: '#9333ea', subs: ['Photographer', 'DJ', 'Catering', 'Florist', 'Videographer'], aliases: ['party', 'wedding', 'music', 'food', 'petrecere', 'nunta', 'dj', 'foto', 'video'] },
  { id: 'edu', label: 'Education', icon: 'book', color: '#059669', subs: ['Maths Tutor', 'Language', 'Music', 'Sports', 'Driving Instructor'], aliases: ['tutor', 'learn', 'school', 'teach', 'meditatii', 'profesor', 'invata', 'condus'] },
  { id: 'tech', label: 'IT & Tech', icon: 'monitor', color: '#0891b2', subs: ['PC Repair', 'Phone Repair', 'Web Design', 'CCTV'], aliases: ['computer', 'laptop', 'phone', 'website', 'reparatie laptop', 'telefon', 'camera'] },
  { id: 'pets', label: 'Pet Care', icon: 'dog', color: '#f97316', subs: ['Dog Walking', 'Grooming', 'Pet Sitting', 'Vet', 'Pet Training'], aliases: ['dog', 'cat', 'animal', 'caine', 'pisica', 'tuns catei', 'dresaj'] },
  { id: 'health', label: 'Health &\nFitness', icon: 'heart', color: '#ef4444', subs: ['Personal Trainer', 'Yoga', 'Nutritionist', 'Physio'], aliases: ['gym', 'workout', 'diet', 'antrenor', 'fitness', 'nutritie', 'sport'] },
  { id: 'legal', label: 'Legal &\nAdmin', icon: 'scale', color: '#6366f1', subs: ['Notary', 'Accounting', 'Translation', 'Consulting'], aliases: ['law', 'taxes', 'avocat', 'contabil', 'acte', 'traduceri'] },
  { id: 'garden', label: 'Gardening', icon: 'leaf', color: '#84cc16', subs: ['Lawn Mowing', 'Hedge Trimming', 'Garden Design', 'Tree Surgery'], aliases: ['grass', 'mow', 'cut', 'tree', 'yard', 'plant', 'gradina', 'iarba', 'tuns iarba', 'gazon', 'copaci', 'peisagistica'] },
  { id: 'office', label: 'Home Office', icon: 'briefcase', color: '#4f46e5', subs: ['Desk Assembly', 'Network Setup', 'Ergonomics', 'Office Design'], aliases: ['desk', 'chair', 'internet', 'birou', 'mobilier', 'retea'] },
  { id: 'life', label: 'Lifestyle', icon: 'smile', color: '#facc15', subs: ['Personal Chef', 'Stylist', 'Life Coach', 'Concierge'], aliases: ['coach', 'chef', 'clothes', 'stilist', 'bucatar'] }
];

export const SUB_IC: Record<string, string> = {
  'Plumber': '🔧', 'Electrician': '⚡', 'Painter': '🖌️', 'Carpenter': '🪑', 'Locksmith': '🔒', 'Handyman': '🛠️',
  'Cleaner': '🧼', 'Deep Clean': '✨', 'Office Cleaning': '🏢',
  'Hairdresser': '✂️', 'Nail Tech': '💅', 'Massage': '💆', 'Makeup': '💄', 'Barber': '💈',
  'Mechanic': '🔩', 'MOT': '📋', 'Valeting': '🚿', 'Recovery': '🚛', 'Transport Auto': '🏎️',
  'Photographer': '📷', 'DJ': '🎧', 'Catering': '🍽️', 'Florist': '💐',
  'Maths Tutor': '📐', 'Language': '🌍', 'Music': '🎵', 'Sports': '⚽',
  'PC Repair': '🖥️', 'Phone Repair': '📱', 'Web Design': '🎨', 'CCTV': '📹',
  'Lawn Mowing': '🌱', 'Hedge Trimming': '✂️', 'Garden Design': '🏡', 'Tree Surgery': '🌳'
};

export const SUB_ALIASES: Record<string, string[]> = {
  'Cleaner': ['clean', 'house', 'curatenie', 'menajera', 'apartament', 'spalat', 'cleaning'],
  'Plumber': ['pipe', 'leak', 'leakage', 'water', 'sink', 'toilet', 'scurgere', 'instalator', 'teava', 'inundatie', 'robinet', 'plumb', 'plumbing'],
  'Electrician': ['wire', 'fuse', 'circuit', 'socket', 'light', 'power', 'electrician', 'priza', 'curent', 'intrerupator', 'tablou', 'scurtcircuit', 'electrical', 'electricity'],
  'Painter': ['paint', 'wall', 'color', 'zugrav', 'vopsea', 'perete', 'painting'],
  'Carpenter': ['wood', 'furniture', 'door', 'usa', 'lemn', 'tamplar', 'carpentry'],
  'Locksmith': ['key', 'lock', 'locked', 'cheie', 'yala', 'deblocare', 'blocat', 'lacat'],
  'Handyman': ['fix', 'repair', 'mount', 'tv', 'instalare', 'montare', 'reparatii', 'bricolaj'],
  'Mechanic': ['engine', 'brakes', 'oil', 'masina', 'mecanic', 'revizie', 'motor', 'frane', 'auto'],
  'Recovery': ['towing', 'tow', 'tractare', 'platforma', 'pana'],
  'Transport Auto': ['car transport', 'platforma', 'transport masini', 'trailer', 'auto transport'],
  'PC Repair': ['laptop', 'computer', 'screen', 'windows', 'virus', 'reparatie piese', 'pc', 'monitor'],
  'Phone Repair': ['phone', 'screen', 'battery', 'telefon', 'ecran', 'baterie', 'display'],
  'Lawn Mowing': ['lawn', 'mow', 'grass', 'iarba', 'gazon', 'tuns', 'curte'],
  'Tree Surgery': ['tree', 'branch', 'copac', 'crengi', 'taiere copaci'],
  'Dog Walking': ['dog', 'walk', 'plimbare', 'caine', 'animale'],
  'Notary': ['notar', 'act', 'legal', 'document', 'acte'],
  'Accounting': ['tax', 'contabil', 'facturi', 'fisc'],
  'Translation': ['translate', 'traducere', 'traducator', 'limba']
};

export const AVC = ['#e8d5b7', '#c4b5a0', '#a8c5d6', '#b8d4c8', '#d6b8c4', '#c5d6b8', '#d6c5b8', '#b8c5d6'];
export const AVE = ['👨‍🔧', '👩‍🎨', '👷', '👩‍🍳', '🧑‍🔧', '💇‍♀️', '👨‍🎨', '📸'];

export const STC: Record<string, string> = {
  hired: '#d97706', // Yellow/Orange: Pending Acceptance
  active: '#059669', // Green: In Progress
  finish_requested: '#2563eb', // Blue: Pending Completion
  completed: '#2d5a5a', // Brand color for completed
  cancelled: '#ef4444',
  declined: '#ef4444',
  disputed: '#dc2626' // Red for dispute
};

export const STL: Record<string, string> = {
  hired: 'Pending Acceptance',
  active: 'In Progress',
  finish_requested: 'Pending Completion',
  completed: 'Completed',
  cancelled: 'Cancelled',
  declined: 'Declined',
  disputed: 'Disputed'
};

const STATIC_PROS: Professional[] = [
  {
    id: 'pro_1',
    name: 'Andrei Popescu',
    email: 'andrei@test.com',
    img: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Plumber',
    rating: 4.9,
    rc: 47,
    jobs: 62,
    loc: 'Abington, Northampton',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: '12+ years plumbing. Emergency repairs, boiler installs, bathroom renovations. City & Guilds qualified.',
    svcs: ['Emergency Repairs', 'Boiler Install', 'Bathroom Reno', 'Drain Unblocking'],
    port: [
      { id: 'p1_1', title: 'Bathroom Before', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&q=80', type: 'before' }, 
      { id: 'p1_2', title: 'Bathroom After', image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=400&q=80', type: 'after' }
    ],
    revs: [{ n: 'Sarah M.', rating: 5, text: 'Brilliant. Fixed leak in minutes.', date: '2w ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '2 PM'] }, { day: 'Tue', dt: '15 Jul', times: ['10 AM'] }],
    isEmergencyAvailable: true
  },
  {
    id: 'pro_h2',
    name: 'Mihai Ionescu',
    email: 'mihai.h@test.com',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Painter',
    rating: 4.7,
    rc: 28,
    jobs: 40,
    loc: 'Duston',
    price: 25,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Professional painter and decorator. Interior and exterior. Clean and reliable.',
    svcs: ['Interior Painting', 'Wallpapering', 'Exterior Gloss'],
    port: [{ id: 'ph2_1', title: 'Living Room', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=400&q=80', type: 'work' }],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['9 AM', '1 PM'] }]
  },
  {
    id: 'pro_3',
    name: 'Tomasz Kowalski',
    email: 'tomasz@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Electrician',
    rating: 4.8,
    rc: 31,
    jobs: 45,
    loc: 'Kingsthorpe',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'NICEIC registered. 10 years. Rewires, fuse boards, EV chargers. English + Polish.',
    svcs: ['Full Rewire', 'Fuse Board', 'EV Charger'],
    port: [{ id: 'p3_1', title: 'Fuse Board', image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80', type: 'work' }],
    revs: [{ n: 'David H.', rating: 5, text: 'Rewired 3-bed in a week. Neat work.', date: '3w ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['8 AM', '1 PM'] }],
    isEmergencyAvailable: true
  },
  {
    id: 'pro_h4',
    name: 'George Vasile',
    email: 'george@test.com',
    img: 'https://images.unsplash.com/photo-1590086782792-42dd2350140d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Carpenter',
    rating: 4.9,
    rc: 52,
    jobs: 70,
    loc: 'Wootton',
    price: 45,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Bespoke furniture, door hanging, flooring. High quality finish.',
    svcs: ['Door Hanging', 'Flooring', 'Custom Shelving'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM', '2 PM'] }]
  },
  {
    id: 'pro_4',
    name: 'Ioana Marinescu',
    email: 'ioana@test.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Cleaner',
    rating: 4.9,
    rc: 67,
    jobs: 95,
    loc: 'Far Cotton',
    price: 15,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: '6 years cleaning. Deep clean, end of tenancy, Airbnb. Own equipment.',
    svcs: ['Regular Clean', 'Deep Clean', 'End of Tenancy'],
    port: [{ id: 'p4_1', title: 'Kitchen After', image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=400&q=80', type: 'after' }],
    revs: [{ n: 'Rachel G.', rating: 5, text: 'Miracle worker! Cleanest handover ever.', date: '1w ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['8 AM', '1 PM'] }]
  },
  {
    id: 'pro_2',
    name: 'Elena Dumitru',
    email: 'elena@test.com',
    img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    catId: 'beauty',
    sub: 'Nail Tech',
    rating: 5.0,
    rc: 83,
    jobs: 120,
    loc: 'Town Centre',
    price: 25,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Award-winning nail tech. Gel, BIAB, nail art. Mobile available.',
    svcs: ['Gel Extensions', 'BIAB', 'Nail Art'],
    port: [{ id: 'p2_1', title: 'Gel Nails', image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=400&q=80', type: 'work' }],
    revs: [{ n: 'Laura P.', rating: 5, text: 'Absolute artist! Lasted 3 weeks.', date: '1w ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['10 AM', '1 PM'] }]
  },
  {
    id: 'pro_b2',
    name: 'Maria Enache',
    email: 'maria.b@test.com',
    img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    catId: 'beauty',
    sub: 'Hairdresser',
    rating: 4.8,
    rc: 45,
    jobs: 60,
    loc: 'Billing',
    price: 45,
    unit: '/session',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Expert in coloring and cutting. 8 years experience.',
    isEmergencyAvailable: true,
    svcs: ['Balayage', 'Haircut', 'Styling'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['11 AM', '3 PM'] }]
  },
  {
    id: 'pro_b3',
    name: 'Carmen Stan',
    email: 'carmen@test.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'beauty',
    sub: 'Massage',
    rating: 4.9,
    rc: 38,
    jobs: 50,
    loc: 'Collingtree',
    price: 55,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Deep tissue and Swedish massage. Relaxing environment.',
    svcs: ['Deep Tissue', 'Swedish Massage', 'Aromatherapy'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM', '4 PM'] }]
  },
  {
    id: 'pro_b4',
    name: 'Alina Popa',
    email: 'alina@test.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'beauty',
    sub: 'Makeup',
    rating: 4.7,
    rc: 25,
    jobs: 35,
    loc: 'Hardingstone',
    price: 40,
    unit: '/session',
    v: { id: 1, dbs: 0, ins: 0 },
    about: 'Bridal and evening makeup. High-end products used.',
    svcs: ['Bridal Makeup', 'Evening Look', 'Makeup Lesson'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['8 AM', '11 AM'] }]
  },
  {
    id: 'pro_b5',
    name: 'Stefan Radu',
    email: 'stefan@test.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'beauty',
    sub: 'Barber',
    rating: 4.9,
    rc: 92,
    jobs: 150,
    loc: 'Town Centre',
    price: 20,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Traditional barbering. Fades, beard trims, hot towel shaves.',
    svcs: ['Skin Fade', 'Beard Trim', 'Hot Towel Shave'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '5 PM'] }]
  },
  {
    id: 'pro_a1',
    name: 'Cristian Matei',
    email: 'cristian@test.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'auto',
    sub: 'Mechanic',
    rating: 4.8,
    rc: 55,
    jobs: 80,
    loc: 'St James',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Mobile mechanic. Diagnostics, servicing, brakes. All makes and models.',
    isEmergencyAvailable: true,
    svcs: ['Diagnostics', 'Full Service', 'Brake Repair'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['8 AM', '2 PM'] }]
  },
  {
    id: 'pro_a2',
    name: 'Adrian Nita',
    email: 'adrian@test.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'auto',
    sub: 'MOT',
    rating: 4.9,
    rc: 110,
    jobs: 200,
    loc: 'Kingsthorpe',
    price: 45,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Certified MOT tester. Fast and fair testing.',
    svcs: ['MOT Class 4', 'MOT Class 7', 'Pre-MOT Check'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['9 AM', '4 PM'] }]
  },
  {
    id: 'pro_a3',
    name: 'Paul Georgescu',
    email: 'paul@test.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'auto',
    sub: 'Valeting',
    rating: 4.7,
    rc: 42,
    jobs: 65,
    loc: 'Wootton',
    price: 30,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Premium car valeting and detailing. Interior and exterior deep clean.',
    svcs: ['Full Valet', 'Interior Detail', 'Machine Polish'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM', '2 PM'] }]
  },
  {
    id: 'pro_a4',
    name: 'Dan Stoica',
    email: 'dan@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'auto',
    sub: 'Recovery',
    rating: 4.9,
    rc: 85,
    jobs: 120,
    loc: 'Northampton',
    price: 60,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: '24/7 breakdown recovery and towing. Fast response times.',
    svcs: ['Breakdown Recovery', 'Vehicle Towing', 'Jump Start'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['12 AM', '11 PM'] }]
  },
  {
    id: 'pro_a5',
    name: 'Victor Lupu',
    email: 'victor@test.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'auto',
    sub: 'Mechanic',
    rating: 4.6,
    rc: 20,
    jobs: 30,
    loc: 'Duston',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Specialist in engine repairs and gearboxes.',
    svcs: ['Engine Rebuild', 'Gearbox Repair', 'Clutch Replacement'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM', '3 PM'] }]
  },
  // NEW HOME PROS
  {
    id: 'pro_h_new1',
    name: 'Stefan Iancu',
    email: 'stefan.iancu@test.com',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Electrician',
    rating: 4.9,
    rc: 88,
    jobs: 124,
    loc: 'Northampton Centre',
    price: 45,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Qualified electrician with 15 years of experience in residential and commercial projects. Specialist in smart home installations.',
    svcs: ['Smart Home Setup', 'Rewiring', 'Lighting Design', 'Emergency Repairs'],
    port: [
      { id: 'phn1_1', title: 'Smart Lighting', image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=400&q=80', type: 'work' }
    ],
    revs: [{ n: 'John D.', rating: 5, text: 'Excellent service, very professional.', date: '1w ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '2 PM'] }]
  },
  {
    id: 'pro_h_new2',
    name: 'Maria Dragomir',
    email: 'maria.d@test.com',
    img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Painter',
    rating: 4.8,
    rc: 42,
    jobs: 65,
    loc: 'Abington',
    price: 30,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Interior design and professional painting. I help you choose the right colors for your home and execute with precision.',
    svcs: ['Interior Painting', 'Color Consulting', 'Decorative Finishes'],
    port: [
      { id: 'phn2_1', title: 'Living Room', image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80', type: 'after' }
    ],
    revs: [{ n: 'Alice W.', rating: 5, text: 'Maria has a great eye for detail!', date: '3d ago' }],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM', '3 PM'] }]
  },
  {
    id: 'pro_h_new3',
    name: 'Radu Vasile',
    email: 'radu.v@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Plumber',
    rating: 4.7,
    rc: 56,
    jobs: 82,
    loc: 'Kingsthorpe',
    price: 55,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Expert plumber specializing in heating systems and leak detection. Available for emergency call-outs 24/7.',
    svcs: ['Leak Detection', 'Heating Systems', 'Pipe Repair', 'Emergency Plumbing'],
    port: [],
    revs: [{ n: 'Mark T.', rating: 4, text: 'Quick response and fixed the issue.', date: '1mo ago' }],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['8 AM', '12 PM', '4 PM'] }],
    isEmergencyAvailable: true
  },
  {
    id: 'pro_h_new4',
    name: 'Elena Stancu',
    email: 'elena.s@test.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Carpenter',
    rating: 5.0,
    rc: 24,
    jobs: 35,
    loc: 'Duston',
    price: 60,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Custom furniture maker and master carpenter. I create unique pieces that fit your space perfectly.',
    svcs: ['Custom Furniture', 'Cabinet Making', 'Wood Restoration'],
    port: [
      { id: 'phn4_1', title: 'Oak Table', image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=400&q=80', type: 'work' }
    ],
    revs: [{ n: 'Robert K.', rating: 5, text: 'The table Elena made is a work of art.', date: '2w ago' }],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['9 AM', '1 PM'] }]
  },
  {
    id: 'pro_h_new5',
    name: 'George Miron',
    email: 'george.m@test.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Handyman',
    rating: 4.6,
    rc: 112,
    jobs: 190,
    loc: 'Wootton',
    price: 25,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Your go-to guy for all those small jobs around the house. Flat-pack assembly, shelf mounting, and general repairs.',
    svcs: ['Flat-pack Assembly', 'Shelf Mounting', 'General Repairs', 'TV Mounting'],
    port: [],
    revs: [{ n: 'Sophie L.', rating: 5, text: 'George was very helpful and fast.', date: '5d ago' }],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['10 AM', '2 PM', '5 PM'] }]
  },
  // ADDITIONAL HOME PROS (3 per subcategory)
  // Plumber
  {
    id: 'pro_h_p1',
    name: 'Ionut Varga',
    email: 'ionut.varga@test.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Plumber',
    rating: 4.8,
    rc: 34,
    jobs: 52,
    loc: 'Abington',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Experienced plumber for all residential needs. Specialized in bathroom installations and emergency repairs.',
    svcs: ['Bathroom Install', 'Emergency Repair', 'Pipework'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '1 PM'] }],
    isEmergencyAvailable: true
  },
  {
    id: 'pro_h_p2',
    name: 'Cristian Stoian',
    email: 'cristian.s@test.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Plumber',
    rating: 4.9,
    rc: 28,
    jobs: 45,
    loc: 'Duston',
    price: 48,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Reliable plumbing services. I focus on quality and customer satisfaction.',
    svcs: ['Leak Repair', 'Radiator Service', 'Taps & Showers'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['10 AM', '2 PM'] }],
    isEmergencyAvailable: true
  },
  {
    id: 'pro_h_p3',
    name: 'Marius Dobre',
    email: 'marius.d@test.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Plumber',
    rating: 4.7,
    rc: 42,
    jobs: 68,
    loc: 'Kingsthorpe',
    price: 52,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Over 10 years of experience in plumbing and heating.',
    svcs: ['Boiler Service', 'Drainage', 'Heating'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['8 AM', '12 PM'] }]
  },
  // Electrician
  {
    id: 'pro_h_e1',
    name: 'Alexandru Negru',
    email: 'alex.negru@test.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Electrician',
    rating: 4.9,
    rc: 45,
    jobs: 78,
    loc: 'Wootton',
    price: 42,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Certified electrician for domestic and commercial work. Safety is my priority.',
    svcs: ['Fuse Box Upgrade', 'Wiring', 'Safety Checks'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM', '3 PM'] }]
  },
  {
    id: 'pro_h_e2',
    name: 'Robert Sandu',
    email: 'robert.s@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Electrician',
    rating: 4.8,
    rc: 32,
    jobs: 55,
    loc: 'Abington',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Specialized in lighting and power installations.',
    svcs: ['LED Lighting', 'Power Sockets', 'Fault Finding'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['10 AM', '4 PM'] }]
  },
  {
    id: 'pro_h_e3',
    name: 'Vlad Ionescu',
    email: 'vlad.i@test.com',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Electrician',
    rating: 5.0,
    rc: 15,
    jobs: 22,
    loc: 'Town Centre',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'High-end electrical solutions for modern homes.',
    svcs: ['Smart Home', 'Home Cinema', 'Automation'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['11 AM'] }]
  },
  // Painter
  {
    id: 'pro_h_pa1',
    name: 'Simona Gherghe',
    email: 'simona.g@test.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Painter',
    rating: 4.9,
    rc: 38,
    jobs: 60,
    loc: 'Duston',
    price: 28,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Professional painting and decorating with a feminine touch.',
    svcs: ['Interior Painting', 'Wallpapering', 'Woodwork'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '2 PM'] }]
  },
  {
    id: 'pro_h_pa2',
    name: 'Daniel Popa',
    email: 'daniel.p@test.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Painter',
    rating: 4.7,
    rc: 52,
    jobs: 85,
    loc: 'Kingsthorpe',
    price: 32,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Exterior and interior painting specialist. Quality materials used.',
    svcs: ['Exterior Painting', 'Fence Painting', 'Ceiling Repair'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['8 AM', '1 PM'] }]
  },
  {
    id: 'pro_h_pa3',
    name: 'Ana Maria Radu',
    email: 'ana.radu@test.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Painter',
    rating: 5.0,
    rc: 20,
    jobs: 30,
    loc: 'Abington',
    price: 35,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Artistic painting and custom murals.',
    svcs: ['Murals', 'Decorative Walls', 'Fine Finishing'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM', '3 PM'] }]
  },
  // Carpenter
  {
    id: 'pro_h_c1',
    name: 'Mihai Dumitrescu',
    email: 'mihai.d@test.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Carpenter',
    rating: 4.9,
    rc: 42,
    jobs: 70,
    loc: 'Wootton',
    price: 55,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Master carpenter for bespoke furniture and structural work.',
    svcs: ['Bespoke Shelving', 'Door Hanging', 'Flooring'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM', '4 PM'] }]
  },
  {
    id: 'pro_h_c2',
    name: 'Sorin Oprea',
    email: 'sorin.o@test.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Carpenter',
    rating: 4.8,
    rc: 35,
    jobs: 58,
    loc: 'Town Centre',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Kitchen fitting and general carpentry.',
    svcs: ['Kitchen Fitting', 'Skirting Boards', 'Decking'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['8 AM', '12 PM'] }]
  },
  {
    id: 'pro_h_c3',
    name: 'Adrian Barbu',
    email: 'adrian.b@test.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Carpenter',
    rating: 4.7,
    rc: 25,
    jobs: 40,
    loc: 'Abington',
    price: 45,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Reliable carpenter for all home improvements.',
    svcs: ['Staircase Repair', 'Window Frames', 'Partition Walls'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['10 AM', '2 PM'] }]
  },
  // Locksmith
  {
    id: 'pro_h_l1',
    name: 'Florin Voinea',
    email: 'florin.v@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Locksmith',
    rating: 5.0,
    rc: 60,
    jobs: 95,
    loc: 'Northampton',
    price: 65,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: '24/7 emergency locksmith. Fast response and non-destructive entry.',
    svcs: ['Emergency Entry', 'Lock Change', 'Security Upgrade'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['Anytime'] }]
  },
  {
    id: 'pro_h_l2',
    name: 'Gabriel Stan',
    email: 'gabriel.s@test.com',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Locksmith',
    rating: 4.9,
    rc: 48,
    jobs: 72,
    loc: 'Duston',
    price: 60,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Expert in smart locks and high-security systems.',
    svcs: ['Smart Lock Install', 'Key Cutting', 'Master Key Systems'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['9 AM', '5 PM'] }]
  },
  {
    id: 'pro_h_l3',
    name: 'Bogdan Luca',
    email: 'bogdan.l@test.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Locksmith',
    rating: 4.8,
    rc: 35,
    jobs: 50,
    loc: 'Kingsthorpe',
    price: 55,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Residential and commercial locksmith services.',
    svcs: ['UPVC Door Locks', 'Safe Opening', 'Burglary Repair'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM', '4 PM'] }]
  },
  // Handyman
  {
    id: 'pro_h_h1',
    name: 'Costel Marin',
    email: 'costel.m@test.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Handyman',
    rating: 4.7,
    rc: 85,
    jobs: 140,
    loc: 'Abington',
    price: 22,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Jack of all trades. I can fix almost anything in your home.',
    svcs: ['Furniture Assembly', 'TV Mounting', 'Curtain Rails'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM', '1 PM', '5 PM'] }]
  },
  {
    id: 'pro_h_h2',
    name: 'Viorel Pasa',
    email: 'viorel.p@test.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Handyman',
    rating: 4.6,
    rc: 70,
    jobs: 115,
    loc: 'Wootton',
    price: 20,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Reliable and affordable handyman services.',
    svcs: ['Painting Touch-ups', 'Gutter Cleaning', 'Fence Repair'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['8 AM', '4 PM'] }]
  },
  {
    id: 'pro_h_h3',
    name: 'Emil Constantinescu',
    email: 'emil.c@test.com',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    catId: 'home',
    sub: 'Handyman',
    rating: 4.9,
    rc: 40,
    jobs: 65,
    loc: 'Town Centre',
    price: 25,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Professional handyman for high-quality repairs and maintenance.',
    svcs: ['Plumbing Repairs', 'Electrical Fixes', 'Tiling'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['10 AM', '2 PM'] }]
  },
  // EVENTS
  {
    id: 'pro_e1',
    name: 'Lucian Brad',
    email: 'lucian@events.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'events',
    sub: 'Photographer',
    rating: 5.0,
    rc: 120,
    jobs: 150,
    loc: 'Northampton',
    price: 150,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Wedding and event photographer. Capturing moments that last forever.',
    isEmergencyAvailable: true,
    svcs: ['Wedding Photography', 'Portrait', 'Event Coverage'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['10 AM', '4 PM'] }]
  },
  {
    id: 'pro_e2',
    name: 'DJ Spark',
    email: 'spark@events.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'events',
    sub: 'DJ',
    rating: 4.9,
    rc: 85,
    jobs: 110,
    loc: 'Town Centre',
    price: 80,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 0 },
    about: 'Professional DJ for weddings, parties, and corporate events.',
    svcs: ['Wedding DJ', 'Party Mix', 'Sound System'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['7 PM', '11 PM'] }]
  },
  {
    id: 'pro_e3',
    name: 'Elena Cook',
    email: 'elena@catering.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'events',
    sub: 'Catering',
    rating: 4.8,
    rc: 60,
    jobs: 80,
    loc: 'Billing',
    price: 25,
    unit: '/person',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Delicious catering for all occasions. Fresh and local ingredients.',
    svcs: ['Buffet', 'Sit-down Meal', 'Canapes'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['12 PM'] }]
  },
  {
    id: 'pro_e4',
    name: 'Rose Florals',
    email: 'rose@events.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'events',
    sub: 'Florist',
    rating: 4.9,
    rc: 40,
    jobs: 55,
    loc: 'Duston',
    price: 50,
    unit: '/bouquet',
    v: { id: 1, dbs: 0, ins: 0 },
    about: 'Beautiful floral arrangements for weddings and events.',
    svcs: ['Wedding Flowers', 'Event Decor', 'Bouquets'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['9 AM'] }]
  },
  {
    id: 'pro_e5',
    name: 'Mark Event',
    email: 'mark@events.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'events',
    sub: 'Photographer',
    rating: 4.7,
    rc: 30,
    jobs: 45,
    loc: 'Wootton',
    price: 100,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Commercial and lifestyle photography.',
    svcs: ['Product Shoots', 'Lifestyle', 'Corporate'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['10 AM'] }]
  },
  // EDU
  {
    id: 'pro_ed1',
    name: 'Prof. John',
    email: 'john@edu.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'edu',
    sub: 'Maths Tutor',
    rating: 5.0,
    rc: 95,
    jobs: 130,
    loc: 'Abington',
    price: 35,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Experienced maths tutor for GCSE and A-Level.',
    isEmergencyAvailable: true,
    svcs: ['GCSE Maths', 'A-Level Maths', 'Calculus'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['4 PM', '6 PM'] }]
  },
  {
    id: 'pro_ed2',
    name: 'Maria Lang',
    email: 'maria@edu.com',
    img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    catId: 'edu',
    sub: 'Language',
    rating: 4.9,
    rc: 70,
    jobs: 100,
    loc: 'Town Centre',
    price: 30,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Native Spanish and French tutor.',
    svcs: ['Spanish Lessons', 'French Lessons', 'Conversation'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['5 PM'] }]
  },
  {
    id: 'pro_ed3',
    name: 'David Music',
    email: 'david@edu.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'edu',
    sub: 'Music',
    rating: 4.8,
    rc: 50,
    jobs: 75,
    loc: 'Kingsthorpe',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Piano and guitar teacher for all ages.',
    svcs: ['Piano Lessons', 'Guitar Lessons', 'Theory'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['3 PM', '5 PM'] }]
  },
  {
    id: 'pro_ed4',
    name: 'Coach Sam',
    email: 'sam@edu.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'edu',
    sub: 'Sports',
    rating: 4.9,
    rc: 40,
    jobs: 60,
    loc: 'Duston',
    price: 25,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Football and tennis coaching for kids.',
    svcs: ['Football Coaching', 'Tennis Lessons', 'Fitness'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['9 AM', '11 AM'] }]
  },
  {
    id: 'pro_ed5',
    name: 'Dr. Smith',
    email: 'smith@edu.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'edu',
    sub: 'Maths Tutor',
    rating: 4.7,
    rc: 25,
    jobs: 40,
    loc: 'Wootton',
    price: 45,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Advanced physics and maths tutoring.',
    svcs: ['Physics', 'Advanced Maths', 'Exam Prep'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['6 PM'] }]
  },
  // TECH
  {
    id: 'pro_t1',
    name: 'Tech Mike',
    email: 'mike@tech.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'tech',
    sub: 'PC Repair',
    rating: 4.9,
    rc: 110,
    jobs: 160,
    loc: 'Town Centre',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Computer and laptop repairs. Hardware and software.',
    isEmergencyAvailable: true,
    svcs: ['Laptop Repair', 'Virus Removal', 'Data Recovery'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '2 PM'] }]
  },
  {
    id: 'pro_t2',
    name: 'Phone Fix',
    email: 'fix@tech.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'tech',
    sub: 'Phone Repair',
    rating: 4.8,
    rc: 90,
    jobs: 140,
    loc: 'Abington',
    price: 30,
    unit: '/repair',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Screen replacements and battery fixes for all phones.',
    svcs: ['Screen Repair', 'Battery Replace', 'Water Damage'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['10 AM', '4 PM'] }]
  },
  {
    id: 'pro_t3',
    name: 'Web Dev Dan',
    email: 'dan@tech.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'tech',
    sub: 'Web Design',
    rating: 5.0,
    rc: 55,
    jobs: 70,
    loc: 'Northampton',
    price: 60,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Modern and responsive website design.',
    svcs: ['UI/UX Design', 'WordPress', 'E-commerce'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['11 AM'] }]
  },
  {
    id: 'pro_t4',
    name: 'Secure CCTV',
    email: 'secure@tech.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'tech',
    sub: 'CCTV',
    rating: 4.9,
    rc: 45,
    jobs: 65,
    loc: 'Kingsthorpe',
    price: 100,
    unit: '/install',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Smart home security and CCTV installation.',
    svcs: ['CCTV Install', 'Smart Alarms', 'Doorbell Cam'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['9 AM'] }]
  },
  {
    id: 'pro_t5',
    name: 'IT Support Leo',
    email: 'leo@tech.com',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    catId: 'tech',
    sub: 'PC Repair',
    rating: 4.7,
    rc: 35,
    jobs: 50,
    loc: 'Duston',
    price: 35,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Remote IT support and network setup.',
    svcs: ['Network Setup', 'IT Support', 'Cloud Backup'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['10 AM'] }]
  },
  // PETS
  {
    id: 'pro_p1',
    name: 'Dog Walker Ben',
    email: 'ben@pets.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'pets',
    sub: 'Dog Walking',
    rating: 5.0,
    rc: 150,
    jobs: 220,
    loc: 'Abington Park',
    price: 15,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Professional dog walking in local parks.',
    svcs: ['Group Walk', 'Solo Walk', 'Puppy Visit'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['8 AM', '12 PM', '4 PM'] }]
  },
  {
    id: 'pro_p2',
    name: 'Pet Groomer Mia',
    email: 'mia@pets.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'pets',
    sub: 'Grooming',
    rating: 4.9,
    rc: 80,
    jobs: 110,
    loc: 'Town Centre',
    price: 40,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Full grooming services for all breeds.',
    svcs: ['Full Groom', 'Bath & Brush', 'Nail Clip'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['9 AM', '2 PM'] }]
  },
  {
    id: 'pro_p3',
    name: 'Sitter Sarah',
    email: 'sarah@pets.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'pets',
    sub: 'Pet Sitting',
    rating: 4.8,
    rc: 65,
    jobs: 90,
    loc: 'Billing',
    price: 25,
    unit: '/day',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'In-home pet sitting and overnight stays.',
    svcs: ['Day Sitting', 'Overnight', 'Cat Feeding'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['10 AM'] }]
  },
  {
    id: 'pro_p4',
    name: 'Vet Clinic Dr. K',
    email: 'vet@pets.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'pets',
    sub: 'Vet',
    rating: 5.0,
    rc: 200,
    jobs: 300,
    loc: 'Northampton',
    price: 50,
    unit: '/consult',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Expert veterinary care and advice.',
    isEmergencyAvailable: true,
    svcs: ['Consultation', 'Vaccination', 'Check-up'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '3 PM'] }]
  },
  {
    id: 'pro_p5',
    name: 'Walker Tom',
    email: 'tom@pets.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'pets',
    sub: 'Dog Walking',
    rating: 4.7,
    rc: 40,
    jobs: 55,
    loc: 'Duston',
    price: 12,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Reliable dog walker for active dogs.',
    svcs: ['Park Walk', 'Exercise', 'Feeding'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['10 AM', '2 PM'] }]
  },
  // HEALTH
  {
    id: 'pro_he1',
    name: 'Trainer Jack',
    email: 'jack@health.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'health',
    sub: 'Personal Trainer',
    rating: 5.0,
    rc: 130,
    jobs: 180,
    loc: 'Gym Centre',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Certified personal trainer for weight loss and muscle gain.',
    svcs: ['Weight Loss', 'Muscle Gain', 'HIIT'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['6 AM', '12 PM', '6 PM'] }]
  },
  {
    id: 'pro_he2',
    name: 'Yoga with Lily',
    email: 'lily@health.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'health',
    sub: 'Yoga',
    rating: 4.9,
    rc: 90,
    jobs: 120,
    loc: 'Studio One',
    price: 15,
    unit: '/class',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Vinyasa and Hatha yoga for all levels.',
    svcs: ['Vinyasa Flow', 'Hatha Yoga', 'Meditation'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['10 AM', '5 PM'] }]
  },
  {
    id: 'pro_he3',
    name: 'Nutri Anna',
    email: 'anna@health.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'health',
    sub: 'Nutritionist',
    rating: 4.8,
    rc: 50,
    jobs: 70,
    loc: 'Northampton',
    price: 60,
    unit: '/consult',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Personalized nutrition plans for health and performance.',
    svcs: ['Meal Plans', 'Diet Analysis', 'Health Coaching'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['11 AM'] }]
  },
  {
    id: 'pro_he4',
    name: 'Physio Phil',
    email: 'phil@health.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'health',
    sub: 'Physio',
    rating: 5.0,
    rc: 110,
    jobs: 150,
    loc: 'Clinic North',
    price: 50,
    unit: '/session',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Expert physiotherapy for sports injuries and recovery.',
    isEmergencyAvailable: true,
    svcs: ['Sports Injury', 'Back Pain', 'Rehab'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '4 PM'] }]
  },
  {
    id: 'pro_he5',
    name: 'Trainer Max',
    email: 'max@health.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'health',
    sub: 'Personal Trainer',
    rating: 4.7,
    rc: 45,
    jobs: 60,
    loc: 'Outdoor Park',
    price: 30,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Outdoor fitness and bootcamps.',
    svcs: ['Bootcamp', 'Park Fitness', 'Strength'],
    port: [],
    revs: [],
    slots: [{ day: 'Sat', dt: '19 Jul', times: ['8 AM'] }]
  },
  // LEGAL
  {
    id: 'pro_l1',
    name: 'Notary Nick',
    email: 'nick@legal.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'legal',
    sub: 'Notary',
    rating: 5.0,
    rc: 180,
    jobs: 250,
    loc: 'Town Centre',
    price: 40,
    unit: '/doc',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Official notary public services for all documents.',
    isEmergencyAvailable: true,
    svcs: ['Document Signing', 'Wills', 'Contracts'],
    port: [],
    revs: [],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM', '1 PM'] }]
  },
  {
    id: 'pro_l2',
    name: 'Accountant Amy',
    email: 'amy@legal.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'legal',
    sub: 'Accounting',
    rating: 4.9,
    rc: 120,
    jobs: 170,
    loc: 'Abington',
    price: 50,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Tax returns and bookkeeping for small businesses.',
    svcs: ['Tax Returns', 'Bookkeeping', 'VAT'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['10 AM', '3 PM'] }]
  },
  {
    id: 'pro_l3',
    name: 'Translator Tim',
    email: 'tim@legal.com',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    catId: 'legal',
    sub: 'Translation',
    rating: 4.8,
    rc: 60,
    jobs: 90,
    loc: 'Remote',
    price: 20,
    unit: '/page',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Certified translation for legal and personal docs.',
    svcs: ['Legal Translation', 'Technical', 'Personal'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['9 AM'] }]
  },
  {
    id: 'pro_l4',
    name: 'Consultant Clara',
    email: 'clara@legal.com',
    img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    catId: 'legal',
    sub: 'Consulting',
    rating: 4.9,
    rc: 45,
    jobs: 65,
    loc: 'Northampton',
    price: 80,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Business strategy and legal consulting.',
    svcs: ['Strategy', 'Legal Advice', 'Compliance'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['11 AM', '2 PM'] }]
  },
  {
    id: 'pro_l5',
    name: 'Notary Paul',
    email: 'paul.l@legal.com',
    img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    catId: 'legal',
    sub: 'Notary',
    rating: 4.7,
    rc: 30,
    jobs: 45,
    loc: 'Duston',
    price: 35,
    unit: '/doc',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Mobile notary services at your convenience.',
    svcs: ['Mobile Notary', 'Affidavits', 'Oaths'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['10 AM'] }]
  },
  // GARDEN
  {
    id: 'g1',
    name: 'Alexandru Ionescu',
    email: 'alex@garden.com',
    catId: 'garden',
    sub: 'Garden Design',
    img: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=256&q=80',
    rating: 4.9,
    rc: 142,
    jobs: 156,
    loc: 'Northampton',
    price: 35,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Specialist în design peisagistic și întreținere grădini cu peste 8 ani de experiență.',
    isEmergencyAvailable: true,
    svcs: ['Lawn Mowing', 'Hedge Trimming', 'Garden Design'],
    port: [
      { id: 'p1', title: 'Before Restoration', image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&w=500&q=80', type: 'before' },
      { id: 'p2', title: 'After Restoration', image: 'https://images.unsplash.com/photo-1558904541-efa8c1965f1e?auto=format&fit=crop&w=500&q=80', type: 'after' }
    ],
    revs: [{ n: 'Maria E.', rating: 5, text: 'Incredible garden transformation!', date: '2d ago' }],
    slots: [{ day: 'Mon', dt: '14 Jul', times: ['9 AM'] }]
  },
  {
    id: 'g2',
    name: 'Mihai Popescu',
    email: 'mihai@garden.com',
    catId: 'garden',
    sub: 'Lawn Mowing',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    rating: 4.8,
    rc: 98,
    jobs: 112,
    loc: 'Northampton',
    price: 30,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 0 },
    about: 'Grădinar pasionat, ofer servicii de tuns iarba și curățat curți.',
    svcs: ['Lawn Mowing', 'Cleanup'],
    port: [],
    revs: [],
    slots: [{ day: 'Tue', dt: '15 Jul', times: ['10 AM'] }]
  },
  {
    id: 'pro_g3',
    name: 'Tree Surgeon Dan',
    email: 'dan@garden.com',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    catId: 'garden',
    sub: 'Tree Surgery',
    rating: 4.9,
    rc: 55,
    jobs: 80,
    loc: 'Abington',
    price: 60,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Professional tree felling and pruning.',
    svcs: ['Tree Felling', 'Pruning', 'Stump Removal'],
    port: [],
    revs: [],
    slots: [{ day: 'Wed', dt: '16 Jul', times: ['8 AM'] }]
  },
  {
    id: 'pro_g4',
    name: 'Hedge Master Leo',
    email: 'leo@garden.com',
    img: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=256&q=80',
    catId: 'garden',
    sub: 'Hedge Trimming',
    rating: 4.7,
    rc: 40,
    jobs: 60,
    loc: 'Duston',
    price: 25,
    unit: '/hr',
    v: { id: 1, dbs: 1, ins: 1 },
    about: 'Expert hedge trimming and shaping.',
    svcs: ['Hedge Trimming', 'Shaping', 'Waste Removal'],
    port: [],
    revs: [],
    slots: [{ day: 'Thu', dt: '17 Jul', times: ['10 AM'] }]
  },
  {
    id: 'pro_g5',
    name: 'Garden Girl Eva',
    email: 'eva@garden.com',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    catId: 'garden',
    sub: 'Garden Design',
    rating: 5.0,
    rc: 35,
    jobs: 50,
    loc: 'Wootton',
    price: 40,
    unit: '/hr',
    v: { id: 1, dbs: 0, ins: 1 },
    about: 'Creative garden design and planting.',
    svcs: ['Planting', 'Design', 'Maintenance'],
    port: [],
    revs: [],
    slots: [{ day: 'Fri', dt: '18 Jul', times: ['9 AM'] }]
  }
];

export const PROS: Professional[] = [...STATIC_PROS, ...GENERATED_PROS];
export const GRANULAR_SERVICES: Record<string, string[]> = {
  'Plumber': [
    'Plumbing Pipe Repair',
    'Plumbing Drain Repair',
    'Plumbing Pipe Installation or Replacement',
    'Water Heater Installation or Replacement',
    'Sink or Faucet Installation or Replacement',
    'Toilet Repair',
    'Water Heater Repair or Maintenance',
    'Shower and Bathtub Repair',
    'Emergency Plumbing',
    'Shower and Bathtub Installation or Replacement',
    'Sink or Faucet Repair',
    'Toilet Installation or Replacement',
    'Gas Line Installation',
    'Garbage Disposal Installation',
    'Septic System Repair, Maintenance or Inspection',
    'Sump Pump Installation or Replacement',
    'Water Treatment System Installation or Replacement',
    'Water Treatment Repair or Maintenance',
    'Septic System Installation or Replacement'
  ],
  'Cleaner': [
    'House Cleaning',
    'Carpet Cleaning',
    'Pressure Washing',
    'Gutter Cleaning and Maintenance',
    'Window Cleaning',
    'Home Organizing',
    'Upholstery and Furniture Cleaning',
    'Commercial Cleaning',
    'Roof Cleaning',
    'Floor Cleaning',
    'Garage, Basement or Attic Cleaning',
    'Tile and Grout Cleaning',
    'Rug Cleaning',
    'Floor Polishing',
    'Commercial Carpet Cleaning',
    'Solar Panel Cleaning'
  ],
  'Electrician': [
    'Electrical and Wiring Repair',
    'Lighting Installation',
    'Fan Installation',
    'Switch and Outlet Installation',
    'Wiring Installation',
    'Switch and Outlet Repair',
    'Circuit Breaker Panel or Fuse Box Repair',
    'Circuit Breaker Panel or Fuse Box Installation',
    'Generator Repair',
    'Generator Installation',
    'Smart Home Setup',
    'EV Charger Installation',
    'Electrical Inspection'
  ],
  'Painter': [
    'Interior Painting',
    'Exterior Painting',
    'Cabinet Painting',
    'Deck Staining',
    'Wallpaper Removal',
    'Drywall Repair',
    'Fence Painting',
    'Stucco Repair',
    'Pressure Washing',
    'Wallpaper Installation'
  ],
  'Handyman': [
    'TV Mounting',
    'Furniture Assembly',
    'Shelf Installation',
    'Door Repair',
    'Drywall Patching',
    'Gutter Cleaning',
    'Deck Repair',
    'Window Treatment Installation',
    'Picture Hanging',
    'Minor Plumbing Fixes',
    'Minor Electrical Fixes'
  ],
  'Carpenter': [
    'Custom Cabinets',
    'Door Installation',
    'Window Frame Repair',
    'Deck Building',
    'Trim & Molding',
    'Framing',
    'Staircase Repair',
    'Wood Furniture Repair'
  ],
  'Mechanic': [
    'Oil Change',
    'Brake Repair',
    'Engine Diagnostic',
    'Battery Replacement',
    'Tire Rotation',
    'Transmission Repair',
    'Suspension Repair',
    'AC Repair',
    'Belt & Hose Replacement'
  ],
  'Hairdresser': [
    'Hair Cut',
    'Hair Color',
    'Highlights',
    'Balayage',
    'Blowout',
    'Hair Treatment',
    'Bridal Styling',
    'Extensions'
  ],
  'Nail Tech': [
    'Manicure',
    'Pedicure',
    'Gel Polish',
    'Acrylic Nails',
    'Nail Art',
    'Dips',
    'Nail Repair'
  ],
  'Photographer': [
    'Wedding Photography',
    'Portrait Sessions',
    'Event Coverage',
    'Real Estate Photography',
    'Commercial / Product',
    'Family Sessions',
    'Headshots'
  ],
  'Dog Walking': [
    'Individual Walk',
    'Group Walk',
    'Puppy Visits',
    'Senior Dog Care',
    'Night Walks'
  ],
  'PC Repair': [
    'Laptop Screen Repair',
    'Virus Removal',
    'Data Recovery',
    'Software Installation',
    'Hardware Upgrade',
    'Network Setup',
    'PC Building'
  ],
  'Lawn Mowing': [
    'Grass Cutting',
    'Edging',
    'Leaf Removal',
    'Fertilizing',
    'Aeration',
    'Weed Control'
  ],
  'Transport Auto': [
    'Open Trailer Transport',
    'Enclosed Trailer Transport',
    'Door-to-Door Delivery',
    'Inoperable Vehicle Transport',
    'Classic Car Transport',
    'Cross-Country Shipping'
  ],
  'Locksmith': [
    'Emergency Lockout',
    'Lock Installation',
    'Lock Repair',
    'Key Duplication',
    'Smart Lock Installation',
    'Safe Opening'
  ],
  'Roofing': [
    'Roof Repair',
    'New Roof Installation',
    'Gutter Repair',
    'Roof Inspection',
    'Skylight Installation',
    'Leak Detection'
  ],
  'Massage': [
    'Deep Tissue',
    'Swedish Massage',
    'Sports Massage',
    'Prenatal Massage',
    'Reflexology',
    'Aromatherapy'
  ],
  'Makeup': [
    'Bridal Makeup',
    'Event Makeup',
    'Editorial Makeup',
    'Makeup Lesson',
    'Eyelash Application'
  ],
  'Barber': [
    'Beard Trim',
    'Fade',
    'Straight Razor Shave',
    'Hot Towel Treatment',
    'Kids Cut'
  ],
  'DJ': [
    'Wedding DJ',
    'Corporate Events',
    'Club / Party DJ',
    'Sound System Rental',
    'Lighting Effects'
  ],
  'Catering': [
    'Buffet Service',
    'Plated Dinner',
    'Cocktail Party',
    'Corporate Lunch',
    'Wedding Catering'
  ],
  'Florist': [
    'Bouquet Arrangement',
    'Event Floral Design',
    'Wedding Flowers',
    'Sympathy Flowers',
    'Flower Delivery'
  ],
  'Maths Tutor': [
    'Primary School Maths',
    'GCSE Maths',
    'A-Level Maths',
    'University Level',
    'Exam Prep'
  ],
  'Language': [
    'English Lessons',
    'French Lessons',
    'Spanish Lessons',
    'German Lessons',
    'Conversation Practice'
  ],
  'Phone Repair': [
    'Screen Replacement',
    'Battery Replacement',
    'Charging Port Repair',
    'Water Damage Repair',
    'Camera Repair'
  ],
  'Personal Trainer': [
    'Weight Loss',
    'Muscle Building',
    'HIIT Training',
    'Nutrition Coaching',
    'Online Coaching'
  ],
  'Notary': [
    'Document Certification',
    'Affidavits',
    'Power of Attorney',
    'Wills & Probate',
    'Identity Verification'
  ],
  'Accounting': [
    'Tax Returns',
    'Bookkeeping',
    'Payroll',
    'VAT Returns',
    'Business Consulting'
  ]
};
